### ISSUE TITLE
:-1: error: ccache: Command not found

### ISSUE THREAD

**Issue by vahidsamimi** [clemenssielaff/ZodiacGraph#1]
Hi , 

i would like to run your code in Qt 5.4.2 but i give this error in Compile : 
:-1: error: ccache: Command not found

What do I exactly have to do to fix it?

many thanks
Vahid

**Comment by clemenssielaff** [comment]
I guess you are using Linux / Unix and don't have ccache installed. Just remove the lines

> unix {
>     QMAKE_CXX = ccache g++
> }

from the .pro file and try to build again. 

ccache is only used to speed up (re-)compilation times, so it is not a necessity for building the software anyway.

Cheers, - Clemens
