### ISSUE TITLE
License conflict: GPLv3 or LGPLv3?

### ISSUE THREAD

**Issue by csaez** [clemenssielaff/ZodiacGraph#3]
Hi Clemens,

First of all thanks for sharing, this project looks great!

I was wondering though, what's the deal with the license? you mention LGPLv3 in the readme and docs but the [LICENSE file](https://github.com/clemenssielaff/ZodiacGraph/blob/master/LICENSE) in the source is GPLv3.

I would love to replace a funky in-house library we have at work with this (or at least play with the idea), but GPL would make it very difficult. Please tell me it is a mistake and you intent to distribute it under LGPL :)

Cheers,
C.

**Comment by clemenssielaff** [comment]
Jup, my bad. Relicensed under MIT license - so go ahead and use it at your heart's content :)

**Comment by csaez** [comment]
Wow, that makes it even better!

Thanks a lot :)
